server:
    # 0 : eureka server 의해서 임의 포트가 할당됨(spring server)
    port: 0

spring:
    rabbitmq: 
        host: rabbitmq-service
        port: 5672
        username: guest
        password: guest

    # mariadb 설정        
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://lgcns-syjeong.cpewmmqqi00g.us-west-2.rds.amazonaws.com/inspire?useSSL=true&requireSSL=true
        username: root
        password: 123456789
    
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MariaDBDialect
      hibernate: 
        # create, create-drop, update, none create하면 서버재기동할 때마다 새로 테이블 만들어지면서 데이터 날라감, 한 번 만들고 나면 none으로 바꾸기
        ddl-auto: create
      # 콘솔출력
      show-sql: true  
    

    data:
        redis:
            host: redis-service
            port: 6379
            password:
            timeout: 6000ms
    
    cloud:
        bus:
            enabled: true